# Generated by Django 5.0.5 on 2024-06-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(null=True, upload_to='producto'),
        ),
    ]
